### ISSUE TITLE
Events not fired

### ISSUE THREAD

**Issue by deka** [kingyue737/nuxt-echarts#9] opened 2024-09-23 08:43 UTC
With 0.2.3, event are not fired 
0.2.2 works as expected.

```html
<script>
const handleFinished = () => {
  console.log('finished')
}
</script>
<template>
  <VChart
    :option="option"
    :init-options="initOptions"
    @finished="handleFinished"
  />
</template>
```

**Comment by kingyue737** [comment] 2024-09-23 09:44
Can you provide a minimal reproduction? I can't reproduce it in my project.

**Comment by kingyue737** [comment] 2024-10-08 03:55
Closing as lack of information

**Closed by kingyue737** 2024-10-08 03:55 UTC
Labels: needs reproduction
